workspace:
  base: /go
  path: src/github.com/VuliTv/go-movie-api

pipeline:
  build:
    image: docker.io/spryhq/golang-dep-swagger:alpine-1.10
    pull: true
    commands:
      - go get -u github.com/golang/dep/cmd/dep
      - dep ensure
      - go test ./... -cover
    environment:
      - CGO=0
      - GOOS=linux
      - GOARCH=amd64

  publish:
    image: plugins/ecr
    repo: 527162640954.dkr.ecr.us-east-1.amazonaws.com/vuli-api
    registry: 527162640954.dkr.ecr.us-east-1.amazonaws.com
    tags: ${DRONE_BUILD_NUMBER}
    when:
      branch: develop
      event: [push, tag, deployment]
  deploy:
    image: joshdvir/drone-ecs-deploy
    cluster: stage-vuli
    service: stage-api
    image_name: 527162640954.dkr.ecr.us-east-1.amazonaws.com/vuli-api:${DRONE_BUILD_NUMBER}
    aws_region: us-east-1 # defaults to us-east-1
    timeout: "500" # defaults to 300 / 5 min
    max: "200" # defaults to 200
    min: "100" # defaults to 100
    when:
      branch: develop
      event: [push, tag, deployment]

  slack:
    image: plugins/slack
    username: drone
    icon_url: https://s3.amazonaws.com/vuli-public-assets/drone.png
    webhook: https://hooks.slack.com/services/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
    when:
      status: [ success, failure ]
    link_names: true
    template: >
      {{#success build.status}}
        build {{build.number}} for {{ repo.name }} on {{ build.event }} succeeded. Good job!
        commit: {{build.commit}}
        author: {{build.author}}
        branch: {{build.branch}}
        link: {{build.link}}
      {{else}}
        build {{build.number}} for {{ repo.name }} on {{ build.event }} failed. Fix me please!
        commit: {{build.commit}}
        author: {{build.author}}
        branch: {{build.branch}}
        link: {{build.link}}
      {{/success}}

