pipeline:
  setup:
    image: docker
    commands:
      - docker build --rm -t 527162640954.dkr.ecr.us-east-1.amazonaws.com/vuli-api:${DRONE_BUILD_NUMBER} .
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
  build:
    image: 527162640954.dkr.ecr.us-east-1.amazonaws.com/vuli-api:${DRONE_BUILD_NUMBER}
    commands:
      - go get
      - go test
  publish:
    image: plugins/ecr
    repo: 527162640954.dkr.ecr.us-east-1.amazonaws.com/vuli-api
    registry: 527162640954.dkr.ecr.us-east-1.amazonaws.com
    tags: ${DRONE_BUILD_NUMBER}
    when:
      branch: develop

  deploy:
    image: joshdvir/drone-ecs-deploy
    cluster: stage-vuli
    service: stage-api
    image_name: 527162640954.dkr.ecr.us-east-1.amazonaws.com/vuli-api:${DRONE_BUILD_NUMBER}
    aws_region: us-east-1 # defaults to us-east-1
    timeout: "500" # defaults to 300 / 5 min
    max: "200" # defaults to 200
    min: "100" # defaults to 100
    when:
      branch: develop
  slack:
    image: plugins/slack
    username: drone
    webhook: https://hooks.slack.com/services/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
    when:
      status: [ success, failure ]
    link_names: true
    template: >
      {{#success build.status}}
        build {{build.number}} forsucceeded. Good job!
        gitref: {{build.ref}}
        author: {{build.author}}
        branch: {{build.branch}}
      {{else}}
        build {{build.number}} failed. Fix me please. <@channelname> <@hoop>
      {{/success}}


