host: api-stage.vuli.tv
consumes:
  - application/json
produces:
  - application/json
schemes:
  - https
info:
  title: Vuli API
  description: Complete API for Movie DB
  termsOfService: http://vuli.tv/terms/
  contact:
    name: API Support
    url: http://www.example.com/support
    email: richard@vuli.tv
  license:
    name: Proprietary
  version: 1.0.1
